export default {
  ADD_JOB_REQUEST: "ADD_JOB_REQUEST",
  REMOVE_ADD_JOB_REQUEST_MESSAGE: "REMOVE_ADD_JOB_REQUEST_MESSAGE",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  JOB_REQUEST_INPUT_CHANGE: "JOB_REQUEST_INPUT_CHANGE",

  FETCH_SECTION_LIST: "FETCH_SECTION_LIST",
  FETCH_USER_JOB_REQUEST: "FETCH_USER_JOB_REQUEST",

  WEB_UPLOAD_REQUEST: "WEB_UPLOAD_REQUEST"
}