export default {
  ADD_JOB_REQUEST: "ADD_JOB_REQUEST",
  REMOVE_ADD_JOB_REQUEST_MESSAGE: "REMOVE_ADD_JOB_REQUEST_MESSAGE",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",

  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  INPUT_CHANGE: "INPUT_CHANGE",

  FETCH_SECTION_LIST: "FETCH_SECTION_LIST",
  FETCH_USER_JOB_REQUEST: "FETCH_USER_JOB_REQUEST",
  FETCH_WEB_UPLOAD_REQUESTS: "FETCH_WEB_UPLOAD_REQUESTS",

  WEB_UPLOAD_REQUEST: "WEB_UPLOAD_REQUEST",
  CLEAR_WEB_UPLOAD_REQUEST: "CLEAR_WEB_UPLOAD_REQUEST",

  UPDATE_USER_INFO: "UPDATE_USER_INFO",
  CLEAR_UPDATE_USER_MESSAGE: "CLEAR_UPDATE_USER_MESSAGE",
}