export default {
  ADD_JOB_REQUEST: "ADD_JOB_REQUEST",
  CURRENT_USER_INFO: "CURRENT_USER_INFO",

  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CHANGE_PASSWORD: "USER_CHANGE_PASSWORD",

  INPUT_CHANGE: "INPUT_CHANGE",

  FETCH_SECTION_LIST: "FETCH_SECTION_LIST",
  FETCH_USER_JOB_REQUEST: "FETCH_USER_JOB_REQUEST",
  FETCH_WEB_UPLOAD_REQUESTS: "FETCH_WEB_UPLOAD_REQUESTS",
  FETCH_JOB_REQUESTS: "FETCH_JOB_REQUESTS",
  FETCH_ADMIN_JOB: "FETCH_ADMIN_JOB",

  WEB_UPLOAD_REQUEST: "WEB_UPLOAD_REQUEST",

  UPDATE_USER_INFO: "UPDATE_USER_INFO",

  GENERATE_CODE: "GENERATE_CODE",
  VALIDATE_CODE: "VALIDATE_CODE",

  CLEAR_MESSAGE: "CLEAR_MESSAGE",

  JOB_REQUEST_ACTION: "JOB_REQUEST_ACTION",
};
